export enum Routes {
  HOME = '/',
  PRODUCTS = '/products/',
  PRODUCTS_ID = '/products/:id',
  BLOG = '/blog',
  ABOUT = '/about',
  NEWS = '/news',
  REVIEWS = '/reviews',
  CONTACTS = '/contacts',
  VOUCHERS = '/vouchers',
  CART = '/cart',
  CATEGORIES = '/categories',
  COMPARE = '/compare',
  FAVORITES = '/favorites',
  LOGIN = '/login',
  BRANDS = '/brands',
  SEARCH = '/search/:query',
  INFO_DELIVERY = '/infoDelivery',
  REFUNDS = '/refunds',
  CERTIFICATE = '/certificate'
}
